require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlimentorefeicaosController do

  # This should return the minimal set of attributes required to create a valid
  # Alimentorefeicao. As you add validations to Alimentorefeicao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlimentorefeicaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all alimentorefeicaos as @alimentorefeicaos" do
      alimentorefeicao = Alimentorefeicao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:alimentorefeicaos).should eq([alimentorefeicao])
    end
  end

  describe "GET show" do
    it "assigns the requested alimentorefeicao as @alimentorefeicao" do
      alimentorefeicao = Alimentorefeicao.create! valid_attributes
      get :show, {:id => alimentorefeicao.to_param}, valid_session
      assigns(:alimentorefeicao).should eq(alimentorefeicao)
    end
  end

  describe "GET new" do
    it "assigns a new alimentorefeicao as @alimentorefeicao" do
      get :new, {}, valid_session
      assigns(:alimentorefeicao).should be_a_new(Alimentorefeicao)
    end
  end

  describe "GET edit" do
    it "assigns the requested alimentorefeicao as @alimentorefeicao" do
      alimentorefeicao = Alimentorefeicao.create! valid_attributes
      get :edit, {:id => alimentorefeicao.to_param}, valid_session
      assigns(:alimentorefeicao).should eq(alimentorefeicao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Alimentorefeicao" do
        expect {
          post :create, {:alimentorefeicao => valid_attributes}, valid_session
        }.to change(Alimentorefeicao, :count).by(1)
      end

      it "assigns a newly created alimentorefeicao as @alimentorefeicao" do
        post :create, {:alimentorefeicao => valid_attributes}, valid_session
        assigns(:alimentorefeicao).should be_a(Alimentorefeicao)
        assigns(:alimentorefeicao).should be_persisted
      end

      it "redirects to the created alimentorefeicao" do
        post :create, {:alimentorefeicao => valid_attributes}, valid_session
        response.should redirect_to(Alimentorefeicao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved alimentorefeicao as @alimentorefeicao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Alimentorefeicao.any_instance.stub(:save).and_return(false)
        post :create, {:alimentorefeicao => {}}, valid_session
        assigns(:alimentorefeicao).should be_a_new(Alimentorefeicao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Alimentorefeicao.any_instance.stub(:save).and_return(false)
        post :create, {:alimentorefeicao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested alimentorefeicao" do
        alimentorefeicao = Alimentorefeicao.create! valid_attributes
        # Assuming there are no other alimentorefeicaos in the database, this
        # specifies that the Alimentorefeicao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Alimentorefeicao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => alimentorefeicao.to_param, :alimentorefeicao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested alimentorefeicao as @alimentorefeicao" do
        alimentorefeicao = Alimentorefeicao.create! valid_attributes
        put :update, {:id => alimentorefeicao.to_param, :alimentorefeicao => valid_attributes}, valid_session
        assigns(:alimentorefeicao).should eq(alimentorefeicao)
      end

      it "redirects to the alimentorefeicao" do
        alimentorefeicao = Alimentorefeicao.create! valid_attributes
        put :update, {:id => alimentorefeicao.to_param, :alimentorefeicao => valid_attributes}, valid_session
        response.should redirect_to(alimentorefeicao)
      end
    end

    describe "with invalid params" do
      it "assigns the alimentorefeicao as @alimentorefeicao" do
        alimentorefeicao = Alimentorefeicao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Alimentorefeicao.any_instance.stub(:save).and_return(false)
        put :update, {:id => alimentorefeicao.to_param, :alimentorefeicao => {}}, valid_session
        assigns(:alimentorefeicao).should eq(alimentorefeicao)
      end

      it "re-renders the 'edit' template" do
        alimentorefeicao = Alimentorefeicao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Alimentorefeicao.any_instance.stub(:save).and_return(false)
        put :update, {:id => alimentorefeicao.to_param, :alimentorefeicao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested alimentorefeicao" do
      alimentorefeicao = Alimentorefeicao.create! valid_attributes
      expect {
        delete :destroy, {:id => alimentorefeicao.to_param}, valid_session
      }.to change(Alimentorefeicao, :count).by(-1)
    end

    it "redirects to the alimentorefeicaos list" do
      alimentorefeicao = Alimentorefeicao.create! valid_attributes
      delete :destroy, {:id => alimentorefeicao.to_param}, valid_session
      response.should redirect_to(alimentorefeicaos_url)
    end
  end

end
